name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'

jobs:
  mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download Modules
        run: go mod download

  test:
    runs-on: ubuntu-latest
    needs:
      - mod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: make test

  generate:
    runs-on: ubuntu-latest
    needs:
      - mod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Generate
        run: make generate

      - name: Check Changes
        run: |
          git add .
          git diff --staged --exit-code
