name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: make test
